
package br.com.research.wsxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonRepository", targetNamespace = "http://wsxml.research.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonRepository {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "includePerson", targetNamespace = "http://wsxml.research.com.br/", className = "br.com.research.wsxml.IncludePerson")
    @ResponseWrapper(localName = "includePersonResponse", targetNamespace = "http://wsxml.research.com.br/", className = "br.com.research.wsxml.IncludePersonResponse")
    @Action(input = "http://wsxml.research.com.br/PersonRepository/includePersonRequest", output = "http://wsxml.research.com.br/PersonRepository/includePersonResponse")
    public String includePerson(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1);

}
